apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pizza-claim #can later be referred to
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi #amount of storage claim